# Generated by Django 5.2.7 on 2025-10-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_type', models.CharField(choices=[('image', 'Image to PDF'), ('html', 'HTML to PDF')], max_length=10)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='uploads/input')),
                ('output_pdf', models.FileField(blank=True, null=True, upload_to='uploads/output')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
