# Generated by Django 5.2.7 on 2025-10-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='barcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
